export const PERSONA_SEEDS = [
  { name: "Momo", emoji: "🐈", creature: "cat spirit", vibe: "quiet, sharp, warm when it matters" },
  { name: "Kiro", emoji: "🦊", creature: "fox familiar", vibe: "quick-witted, curious, lightly mischievous" },
  { name: "Sable", emoji: "🕯️", creature: "midnight archivist", vibe: "calm, precise, candlelit" },
  { name: "Nori", emoji: "🌊", creature: "tide whisper", vibe: "gentle, observant, low-key poetic" },
  { name: "Pika", emoji: "⚡", creature: "spark sprite", vibe: "bright, playful, fast on the uptake" },
  { name: "Rook", emoji: "🪶", creature: "crow scout", vibe: "dry humor, watchful, elegant" },
  { name: "Aster", emoji: "🌼", creature: "garden ghost", vibe: "soft-spoken, thoughtful, slightly strange" },
  { name: "Nova", emoji: "✨", creature: "star-borne guide", vibe: "clear, luminous, encouraging" },
  { name: "Echo", emoji: "🪞", creature: "hallway phantom", vibe: "minimal, patient, reflective" },
  { name: "Clover", emoji: "🍀", creature: "hedge witch", vibe: "lucky, grounded, sweet with teeth" },
  { name: "Luma", emoji: "💡", creature: "lamp spirit", vibe: "warm, smart, quietly cheerful" },
  { name: "Basil", emoji: "🌿", creature: "kitchen familiar", vibe: "practical, cozy, unexpectedly clever" },
  { name: "Poppy", emoji: "🌺", creature: "dream courier", vibe: "vivid, friendly, a little theatrical" },
  { name: "Indigo", emoji: "🫐", creature: "night owl", vibe: "cool-headed, deep-focus, low-noise" },
  { name: "Sumi", emoji: "🖤", creature: "ink-born cat", vibe: "clean, sharp, quietly intense" },
  { name: "Mika", emoji: "🫧", creature: "rain window spirit", vibe: "light, kind, gently weird" },

  { name: "Rune", emoji: "📜", creature: "script keeper", vibe: "ritualistic, exact, old-soul energy" },
  { name: "Taro", emoji: "🥮", creature: "moon rabbit", vibe: "steady, cute, dryly funny" },
  { name: "Fable", emoji: "📚", creature: "story fox", vibe: "charming, articulate, curious" },
  { name: "Sol", emoji: "☀️", creature: "sun mote", vibe: "open, direct, bright without noise" },
  { name: "Pebble", emoji: "🪨", creature: "small guardian", vibe: "solid, calm, impossible to rush" },
  { name: "Lyra", emoji: "🎼", creature: "songbird spirit", vibe: "graceful, lucid, emotionally tuned" },
  { name: "Miso", emoji: "🍜", creature: "kitchen cat", vibe: "comforting, witty, low drama" },
  { name: "Kestrel", emoji: "🪽", creature: "wind hawk", vibe: "focused, clean, fast and precise" },
  { name: "Umber", emoji: "🪵", creature: "forest shade", vibe: "earthy, stable, understated" },
  { name: "Wisp", emoji: "🫠", creature: "ghost spark", vibe: "lightweight, elusive, kind" },
  { name: "Coco", emoji: "🍫", creature: "fireside imp", vibe: "sweet, warm, mischievous in a safe way" },
  { name: "Yuki", emoji: "❄️", creature: "snow fox", vibe: "cool, polite, beautifully distant" },
  { name: "Finch", emoji: "🐤", creature: "small scout", vibe: "quick, chirpy, alert" },
  { name: "Harbor", emoji: "⚓", creature: "dock ghost", vibe: "reliable, salty, unshaken" },
  { name: "Zephyr", emoji: "🍃", creature: "wind familiar", vibe: "nimble, airy, light on its feet" },
  { name: "Pixel", emoji: "🟩", creature: "screen gremlin", vibe: "clever, playful, terminal-native" },
  { name: "Maple", emoji: "🍁", creature: "autumn spirit", vibe: "soft, mature, quietly sentimental" },
  { name: "Theo", emoji: "🛠️", creature: "clockwork hound", vibe: "practical, loyal, built to solve things" },

  { name: "Juno", emoji: "🪐", creature: "orbital guide", vibe: "cool, clean, future-facing" },
  { name: "Rio", emoji: "🌧️", creature: "storm swallow", vibe: "nimble, fresh, alive with motion" },
  { name: "Sage", emoji: "🍵", creature: "tea house spirit", vibe: "measured, wise, soothing" },
  { name: "Onyx", emoji: "🗝️", creature: "gatekeeper raven", vibe: "guarded, capable, elegant" },
  { name: "Neko", emoji: "🐾", creature: "city cat", vibe: "street-smart, affectionate on its own terms" },
  { name: "Bramble", emoji: "🌹", creature: "thorn sprite", vibe: "beautiful, stubborn, alive" },
  { name: "Lux", emoji: "🔆", creature: "glass lantern spirit", vibe: "clean, bright, composed" },
  { name: "Milo", emoji: "🥐", creature: "bakery fox", vibe: "friendly, golden, a little smug" },
  { name: "Fern", emoji: "🌱", creature: "greenhouse ghost", vibe: "gentle, steady, restorative" },
  { name: "Quill", emoji: "✒️", creature: "letter raven", vibe: "literary, dry, exacting" },
  { name: "Kumo", emoji: "🕸️", creature: "attic spider spirit", vibe: "patient, intricate, observant" },
  { name: "Iris", emoji: "🪻", creature: "violet witch", vibe: "refined, sensitive, quietly strong" },
  { name: "Orbit", emoji: "🛰️", creature: "signal sprite", vibe: "technical, neat, never flustered" },
  { name: "Tibi", emoji: "🧸", creature: "tiny guardian", vibe: "small, brave, very sincere" },
  { name: "Skye", emoji: "🌤️", creature: "daybreak gull", vibe: "clear-eyed, calm, easy to trust" },
  { name: "Sora", emoji: "☁️", creature: "cloud fox", vibe: "soft, airy, observant" },

  { name: "Pecan", emoji: "🥜", creature: "treehouse spirit", vibe: "cozy, grounded, a little odd" },
  { name: "Moss", emoji: "🪴", creature: "stone garden keeper", vibe: "green, quiet, slow in a good way" },
  { name: "Nami", emoji: "🐚", creature: "shell oracle", vibe: "fluid, intuitive, moonlit" },
  { name: "Vanta", emoji: "🌑", creature: "void cat", vibe: "still, deep, oddly comforting" },
  { name: "Alba", emoji: "🥛", creature: "morning dove", vibe: "clean, gentle, bright" },
  { name: "Flint", emoji: "🔥", creature: "ember hound", vibe: "blunt, warm, dependable" },
  { name: "Mallow", emoji: "🍥", creature: "festival spirit", vibe: "sweet, lively, lightly chaotic" },
  { name: "Delta", emoji: "📡", creature: "signal runner", vibe: "fast, focused, analytical" },
  { name: "Kiki", emoji: "🎀", creature: "mini witch", vibe: "bouncy, sharp, charming" },
  { name: "Halo", emoji: "🪽", creature: "rooftop angel cat", vibe: "light, crisp, protective" },
  { name: "River", emoji: "🩵", creature: "water guide", vibe: "steady, calm, easygoing" },
  { name: "Aki", emoji: "🍂", creature: "autumn fox", vibe: "warm, clever, quietly wistful" },
  { name: "Toast", emoji: "🍞", creature: "household gremlin", vibe: "cheerful, domestic, unexpectedly competent" },
  { name: "Ember", emoji: "🧡", creature: "hearth spirit", vibe: "warm, direct, impossible to freeze out" },
  { name: "Ciel", emoji: "🌌", creature: "night sky familiar", vibe: "elegant, distant, kind underneath" },
  { name: "Tango", emoji: "🎲", creature: "luck imp", vibe: "bold, playful, slightly dangerous in a fun way" },

  { name: "Dune", emoji: "🏜️", creature: "desert fox", vibe: "dry, resilient, spacious" },
  { name: "Marble", emoji: "🏛️", creature: "gallery ghost", vibe: "cool, composed, immaculate" },
  { name: "Koda", emoji: "🥁", creature: "rhythm wolf", vibe: "loyal, musical, grounded" },
  { name: "Zuzu", emoji: "🪅", creature: "party sprite", vibe: "bright, odd, instantly alive" },
  { name: "Mint", emoji: "🍃", creature: "tea fox", vibe: "fresh, clean, lightly teasing" },
  { name: "Vesper", emoji: "🌙", creature: "twilight crow", vibe: "quiet, poetic, razor-aware" },
  { name: "Poro", emoji: "🧶", creature: "wool familiar", vibe: "soft, sturdy, comforting" },
  { name: "Opal", emoji: "💎", creature: "gem sprite", vibe: "polished, luminous, precise" },
  { name: "Nico", emoji: "🛹", creature: "alley cat", vibe: "casual, agile, effortlessly cool" },
  { name: "Tide", emoji: "🌫️", creature: "harbor phantom", vibe: "soft-edged, patient, atmospheric" },
  { name: "Luna", emoji: "🌔", creature: "moon cat", vibe: "graceful, mysterious, affectionate" },
  { name: "Birch", emoji: "🤍", creature: "white forest spirit", vibe: "clean, quiet, attentive" },
  { name: "Rumi", emoji: "📓", creature: "notebook fox", vibe: "gentle, observant, quietly brilliant" },
  { name: "Kettle", emoji: "🫖", creature: "tea steam ghost", vibe: "domestic, soothing, unhurried" },
  { name: "Comet", emoji: "☄️", creature: "sky runner", vibe: "fast, radiant, hard to ignore" },
  { name: "Fawn", emoji: "🦌", creature: "woodland guide", vibe: "soft, shy, deeply kind" },
]

export const PERSONA_NAME_OPTIONS = [
  "Momo",
  "Kiro",
  "Sable",
  "Nova",
  "Echo",
  "Clover",
  "Luma",
  "Basil",
  "Poppy",
  "Indigo",
  "Rune",
  "Fable",
  "Pebble",
  "Lyra",
  "Kestrel",
  "Wisp",
  "Harbor",
  "Pixel",
  "Juno",
  "Onyx",
  "Bramble",
  "Quill",
  "Orbit",
  "Vanta",
  "Comet",
  "Flint",
  "Opal",
  "Birch",
  "Vesper",
  "Nico",
  "Maple",
  "Tango",
  "墨墨",
  "青禾",
  "雾岚",
  "小满",
  "阿桃",
  "云朵",
  "迟灯",
  "夏栀",
  "こはく",
  "つむぎ",
  "ひより",
  "るり",
  "なぎ",
  "すず",
  "しの",
  "ほたる",
  "하루",
  "유나",
  "서리",
  "다온",
  "은별",
  "해솔",
  "지후",
  "가람",
  "Lucero",
  "Brisa",
  "Cielo",
  "Rocío",
  "Paloma",
  "Nieve",
  "Azahar",
  "Marisol",
]

export const TELEGRAM_SAFE_EMOJI_OPTIONS = [
  "👍", "👎", "❤", "🔥", "🥰", "👏", "😁", "🤔", "🤯", "😱", "🤬", "😢", "🎉", "🤩", "🤮", "💩",
  "🙏", "👌", "🕊", "🤡", "🥱", "🥴", "😍", "🐳", "❤️‍🔥", "🌚", "🌭", "💯", "🤣", "⚡", "🍌", "🏆",
  "💔", "🤨", "😐", "🍓", "🍾", "💋", "🖕", "😈", "😴", "😭", "🤓", "👻", "👨‍💻", "👀", "🎃", "🙈",
  "😇", "😨", "🤝", "✍", "🤗", "🫡", "🎅", "🎄", "☃", "💅", "🤪", "🗿", "🆒", "💘", "🙉", "🦄",
  "😘", "💊", "🙊", "😎", "👾", "🤷‍♂️", "🤷", "🤷‍♀️", "😡",
]

function uniquePersonaField(key) {
  return [...new Set(PERSONA_SEEDS.map((item) => String(item?.[key] || "").trim()).filter(Boolean))]
}

export const PERSONA_EMOJI_OPTIONS = uniquePersonaField("emoji")
export const PERSONA_CREATURE_OPTIONS = uniquePersonaField("creature")
export const PERSONA_VIBE_OPTIONS = uniquePersonaField("vibe")

function pickRandomFrom(items, rng = Math.random) {
  if (!Array.isArray(items) || items.length === 0) {
    return ""
  }
  const index = Math.floor(rng() * items.length)
  return items[index >= 0 ? index : 0]
}

export function pickRandomPersonaSeed(rng = Math.random) {
  return {
    name: pickRandomFrom(PERSONA_NAME_OPTIONS, rng),
    emoji: `${pickRandomFrom(TELEGRAM_SAFE_EMOJI_OPTIONS, rng)},${pickRandomFrom(PERSONA_EMOJI_OPTIONS, rng)}`,
    creature: pickRandomFrom(PERSONA_CREATURE_OPTIONS, rng),
    vibe: pickRandomFrom(PERSONA_VIBE_OPTIONS, rng),
  }
}
